# mkdocs.yml
site_name: cachium
site_description: Sync and async cache for your Python applications.
site_url: https://zoola969.github.io/cachium
repo_url: https://github.com/zoola969/cachium
repo_name: https://github.com/zoola969/cachium
edit_uri: edit/main/

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md
  - API Reference:
    - Overview: api/index.md
    - Cache: api/cache.md
    - Builders: api/builders.md
    - Serializers: api/serializers.md
    - Utilities: api/utilities.md
  - Examples: examples.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            heading_level: 3
            show_category_heading: true
            show_signature_annotations: true
            merge_init_into_class: true
            members_order: source
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_root_heading: true
            show_if_no_docstring: true
            filters: ["!^_[^_]"]            # Exclude private members (starting with single _)
watch:
  - cachium/
  - docs/
